-- ======================================================
-- Aggregation Analysis: Zepto E-commerce Data
-- ======================================================
-- Focus: Revenue, discounts, inventory weight by category
-- SQL Level: GROUP BY, SUM, AVG, ORDER BY
-- ======================================================


-- Q1: Estimated revenue generated by each product category
SELECT
    category,
    SUM(discountedSellingPrice * availableQuantity) AS total_revenue
FROM zepto
GROUP BY category
ORDER BY total_revenue DESC;


-- Q2: Top 5 categories offering the highest average discount percentage
SELECT
    category,
    ROUND(AVG(discountPercent), 2) AS avg_discount_percentage
FROM zepto
GROUP BY category
ORDER BY avg_discount_percentage DESC
LIMIT 5;


-- Q3: Total inventory weight by product category
SELECT
    category,
    SUM(weightInGms * availableQuantity) AS total_inventory_weight
FROM zepto
GROUP BY category
ORDER BY total_inventory_weight DESC;
